name: Code_Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    environment: main
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.2]
        stability: [prefer-stable]
        minimum-stability: [stable]
        symfony-version: [7.0.*]
        is-current: [false]
        include:
          - php: '8.3'
            symfony-version: 7.0.*
            stability: prefer-stable
          - php: '8.4'
            symfony-version: 7.0.*
            stability: prefer-stable
          - php: '8.4'
            symfony-version: 7.4.*
            stability: prefer-stable
            minimum-stability: dev
            is-current: true

    name: PHP ${{ matrix.php }} - ${{ matrix.symfony-version }} - ${{ matrix.stability }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-packages-${{ hashFiles('composer.lock') }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer config minimum-stability ${{ matrix.minimum-stability }}
          composer update --no-interaction --prefer-dist --no-security-blocking

      - name: PHP-CS-Fixer
        continue-on-error: ${{ !matrix.is-current }}
        run: vendor/bin/php-cs-fixer fix --ansi -v --dry-run

      - name: PHPStan
        continue-on-error: ${{ !matrix.is-current }}
        run: vendor/bin/phpstan analyse src tests --level 9

      - name: Execute tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: weak
        run: vendor/bin/phpunit

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: SonarSource/sonarqube-scan-action@v6
